version: 2.1
executors:
    rust-image:
        docker:
            - image: cimg/rust:1.51.0
commands:
    prepare:
        description: Prepare the rust image by updating rust and a
        parameters:
            target:
                type: string
                default: thumbv7m-none-eabi
        steps:
            - checkout
            - run: rustup self update
            - run: rustup target add << parameters.target >>
            - run: cargo update
jobs:
    check_style_guidelines:
        executor: rust-image
        steps:
            - checkout
            - run: rustup component add rustfmt
            - run: cargo fmt --all -- --check
    run_tests:
        executor: rust-image
        steps:
            - checkout
            - run: cargo test --lib --target x86_64-unknown-linux-gnu
            - run: cargo test --doc --target x86_64-unknown-linux-gnu
    build:
        executor: rust-image
        parameters:
            target:
                type: string
                default: thumbv7m-none-eabi
        steps:
            - prepare:
                target: << parameters.target >>
            - run: cargo build --target << parameters.target >> --all-features --release
            - run: cargo clean --doc
            - run: cargo clean --doc --target << parameters.target >>
            - run: cargo doc --all-features --target << parameters.target >>
    build_STM32F103_examples:
        executor: rust-image
        steps:
            - prepare:
                target: thumbv7m-none-eabi
            - run: cargo build --target thumbv7m-none-eabi --example bmp_i2c
            - run: cargo build --target thumbv7m-none-eabi --example graphics
            - run: cargo build --target thumbv7m-none-eabi --example graphics_i2c
            - run: cargo build --target thumbv7m-none-eabi --example graphics_i2c_72x40
            - run: cargo build --target thumbv7m-none-eabi --example graphics_i2c_128x32
            - run: cargo build --target thumbv7m-none-eabi --example image_i2c
            - run: cargo build --target thumbv7m-none-eabi --example noise_i2c
            - run: cargo build --target thumbv7m-none-eabi --example pixelsquare
            - run: cargo build --target thumbv7m-none-eabi --example rotation_i2c
            - run: cargo build --target thumbv7m-none-eabi --example rtic_brightness
            - run: cargo build --target thumbv7m-none-eabi --example rtic_dvd
            - run: cargo build --target thumbv7m-none-eabi --example terminal_i2c
            - run: cargo build --target thumbv7m-none-eabi --example text_i2c
    build_raspberry_pi_examples:
        executor: rust-image
        steps:
            - prepare:
                target: armv7-unknown-linux-gnueabihf
            - run: sudo apt update
            - run: sudo apt install -y gcc-arm-linux-gnueabihf
            - run: cargo build --target armv7-unknown-linux-gnueabihf --example text_raspberry_pi
workflows:
    build_all_targets:
        jobs:
            - check_style_guidelines
            - run_tests
            - build:
                  name: build-target-arm-unknown-linux-gnueabi
                  target: arm-unknown-linux-gnueabi
            - build:
                  name: build-target-armv7-unknown-linux-gnueabihf
                  target: armv7-unknown-linux-gnueabihf
            - build:
                  name: build-target-x86_64-unknown-linux-gnu
                  target: x86_64-unknown-linux-gnu
            - build:
                  name: build-target-x86_64-unknown-linux-musl
                  target: x86_64-unknown-linux-musl
            - build:
                  name: build-target-thumbv6m-none-eabi
                  target: thumbv6m-none-eabi
            - build:
                  name: build-target-thumbv7em-none-eabi
                  target: thumbv7em-none-eabi
            - build:
                  name: build-target-thumbv7em-none-eabihf
                  target: thumbv7em-none-eabihf
            - build:
                  name: build-target-thumbv7m-none-eabi
                  target: thumbv7m-none-eabi
            - build_STM32F103_examples
            - build_raspberry_pi_examples